baseurl = "https://hbpmedical.github.io/development-guidelines/"
canonifyurls = true
googleAnalytics = "UA-80660232-2"
languageCode = "en-uk"
metadataformat = "yaml"
theme = "hugo-theme-learn"
title = "MIP development guidelines"
[blackfriday]
fractions = true
plainIDAnchors = true
smartDashes = true
smartypants = true
[[menu.intro]]
name = "Introduction"
url = "/intro"
weight = 10
[[menu.main]]
name = "Maturity and TRLs"
url = "/maturity"
weight = 10
[[menu.main]]
name = "QA and testing"
url = "/qa"
weight = 20
[[menu.main]]
name = "Github"
url = "/github"
weight = 30
[[menu.main]]
name = "Docker"
url = "/docker"
weight = 40
[[menu.main]]
name = "Python"
url = "/python"
weight = 50
[[menu.main]]
name = "Java"
url = "/java"
weight = 60
[[menu.main]]
name = "Scala"
url = "/scala"
weight = 70
[[menu.main]]
name = "Matlab"
url = "/matlab"
weight = 80
[[menu.main]]
name = "R"
url = "/r"
weight = 90
[[menu.main]]
name = "MIP development guidelines"
url = "/"
weight = 0

[params]
author = "HBP SP8 team"
copyright = "Released under the MIT license"
custom_css = []
custom_js = []
description = "Development guidelines for the Medical Informatics Platform of the Human Brain Project."
favicon = ""
highlight_css = ""
logo = "images/hbp.png"
permalink = "#"
provider = ""
repo_url = "https://github.com/HBPMedical/development-guidelines"
version = ""
editURL = "https://github.com/HBPMedical/development-guidelines/edit/master/content/"
menu = [ "intro", "maturity", "qa", "github", "docker", "python", "java", "scala", "matlab", "r" ]
[params.font]
code = "Ubuntu Mono"
text = "Ubuntu"
[params.palette]
accent = "teal"
primary = "red"
[social]
github = "HBPMedical"

aliases = [
    "/intro/",
    "/"
]
